function prfdlrp(varargin);
% prfdlrp( [...] );
% L2R Pkts per sec
h = timeplot({'L2R_Packet_rate','L2R_Int_packets_tx','L2R_Int_packets_rx'}, ...
      'L2R Pkts per sec', ...
      'Pkts per sec', ...
      {'rate','tx','rx'}, ...
      varargin{:} );
