function prfdlrl(varargin);
% prfdlrl( [...] );
% L2R Latency
h = timeplot({'L2R_Int_min_latency','L2R_Int_mean_latency','L2R_Int_max_latency'}, ...
      'L2R Latency', ...
      'Latency', ...
      {'min','mean','max'}, ...
      varargin{:} );
