function prfdlrb(varargin);
% prfdlrb( [...] );
% L2R Bytes per sec
h = timeplot({'L2R_Int_bytes_tx','L2R_Int_bytes_rx'}, ...
      'L2R Bytes per sec', ...
      'Bytes per sec', ...
      {'L2R\_Int\_bytes\_tx','L2R\_Int\_bytes\_rx'}, ...
      varargin{:} );
