function prfdrlp(varargin);
% prfdrlp( [...] );
% R2L Pkts per sec
h = timeplot({'R2L_Packet_rate','R2L_Int_packets_tx','R2L_Int_packets_rx'}, ...
      'R2L Pkts per sec', ...
      'Pkts per sec', ...
      {'rate','tx','rx'}, ...
      varargin{:} );
